version: "3"
services:
  # backend:
  #   build:
  #     context: backend
  #     dockerfile: dev.Dockerfile
  #   environment:
  #     DATABASE_URL: postgres://${PG_USERNAME}:${PG_PASSWORD}@db/${PG_DATABASE}
  #     PEPPER: ${PEPPER}
  #     ROCKET_ADDRESS: 0.0.0.0
  #     ROCKET_PORT: 8000
  #   ports:
  #     - ${BACKEND_PORT}:8000
  #   volumes:
  #     - ./backend:/app
  #     - /app/target

  frontend:
    build:
      context: frontend
      dockerfile: dev.Dockerfile
    environment:
      BACKEND_ADDRESS: http://localhost:8000
    ports:
      - ${FRONTEND_PORT}:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    extra_hosts:
      host.docker.internal: host-gateway

  db:
    image: postgres:13.2
    environment:
      POSTGRES_DB: ${PG_DATABASE}
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - ${PG_LOCAL_PORT}:5432

  adminer:
    image: adminer
    ports:
      - ${ADMINER_PORT}:8080

  redis:
    image: redis:6.2
    ports:
      - ${REDIS_PORT}:6379


  redis-ui:
    image: patrikx3/p3x-redis-ui:2021.4.162
    ports:
      - ${REDIS_UI_PORT}:7843
    volumes:
      - /settings
