name: Backend CI V2

on:
  push:
    tags:
      - 'backend-v*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Strip tag name prefix
      id: tag
      run: |
        version=$(echo '${{ github.ref_name }}' | sed -e 's/^backend-//')
        echo "tag=viddem/accounts-rs-backend:$version" >> $GITHUB_ENV
    - name: Print tag
      id: debug_tag
      run: |
        echo "Deploying to docker tag [${{ steps.tag.outputs.
          
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $TAG
