name: Backend CD

on:
  push:
    tags:
      - 'backend-v*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Strip tag name prefix
      id: tag
      run: |
        version=$(echo '${{ github.ref_name }}' | sed -e 's/^backend-//')
        echo "tag=viddem/accounts-rs-backend:$version" >> $GITHUB_OUTPUT
    - name: Print tag
      id: debug_tag
      run: |
        echo "Deploying to docker tag [${{ steps.tag.outputs.tag }}]"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # - name: Build and push
    #   uses: docker/build-push-action@v4
    #   with:
    #     context: ./backend
    #     push: true
    #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/accounts-rs-backend:${{  }}
