on:
  push:
    tags:
      - '*'
 
jobs:
  build:
    uses:
      ./github/workflows/backend.yml@v1

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup up docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          context: ./backend
          file: ./backend/Dockerfile

