on:
  push:
    tags:
      - 'backend-v*'
 
name: "Backend CD"

jobs:
  build:
    uses:
      ./.github/workflows/backend.yml

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Strip tag name prefix
        run: echo "TAG=$(echo 'backend-v1.2.3" | sed -e 's/^backend-//')" >> $GITHUB_ENV
        # run: echo "TAG=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV
      - name: Print tag name
        run: echo "TAG=[$TAG]"

      - name: Setup up docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./backend
          file: ./backend/Dockerfile
          tags: viddem/accounts-rs-backend:${{ github.ref_name }}
