on:
  push:
    tags:
      - '*'
 
name: "Backend CD"

jobs:
  build:
    uses:
      ./.github/workflows/backend.yml

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup up docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./backend
          file: ./backend/Dockerfile
          tags: viddem/accounts-rs-backend:$GITHUB_REF_NAME
